export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";

export const GET_SLIDERS = "GET_SLIDERS";
export const GET_SLIDERS_LOADING = "GET_SLIDERS_LOADING";

export const GET_CARTS = "GET_CARTS";
export const GET_CARTS_LOADING = "GET_CARTS_LOADING";
export const POST_CARTS_LOADING = "POST_CARTS_LOADING";
export const EMPTY_CART_MESSAGE = "EMPTY_CART_MESSAGE";
export const POST_CARTS_DATA = "POST_CARTS_DATA";
export const UPDATE_CARTS_DATA = "UPDATE_CARTS_DATA";
export const DELETE_CARTS_DATA = "DELETE_CARTS_DATA";
